name = "sortable"
version = "2.0.0"
target = "javascript"

description = "A drag-and-drop sortable list library for Gleam/Lustre"
licenses = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "sortable" }

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
lustre = ">= 5.1.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
